//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4_Site.XMLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Park", Namespace="http://schemas.datacontract.org/2004/07/Project4_XMLServices")]
    [System.SerializableAttribute()]
    public partial class Park : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Established_InField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FounderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] Neighboring_StatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Park_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reservation_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reservation_UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Established_In {
            get {
                return this.Established_InField;
            }
            set {
                if ((object.ReferenceEquals(this.Established_InField, value) != true)) {
                    this.Established_InField = value;
                    this.RaisePropertyChanged("Established_In");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Founder {
            get {
                return this.FounderField;
            }
            set {
                if ((object.ReferenceEquals(this.FounderField, value) != true)) {
                    this.FounderField = value;
                    this.RaisePropertyChanged("Founder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Neighboring_States {
            get {
                return this.Neighboring_StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.Neighboring_StatesField, value) != true)) {
                    this.Neighboring_StatesField = value;
                    this.RaisePropertyChanged("Neighboring_States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Park_Type {
            get {
                return this.Park_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Park_TypeField, value) != true)) {
                    this.Park_TypeField = value;
                    this.RaisePropertyChanged("Park_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reservation_Address {
            get {
                return this.Reservation_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Reservation_AddressField, value) != true)) {
                    this.Reservation_AddressField = value;
                    this.RaisePropertyChanged("Reservation_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reservation_Url {
            get {
                return this.Reservation_UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.Reservation_UrlField, value) != true)) {
                    this.Reservation_UrlField = value;
                    this.RaisePropertyChanged("Reservation_Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XMLService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPark", ReplyAction="http://tempuri.org/IService1/addParkResponse")]
        void addPark(Project4_Site.XMLService.Park park);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPark", ReplyAction="http://tempuri.org/IService1/addParkResponse")]
        System.Threading.Tasks.Task addParkAsync(Project4_Site.XMLService.Park park);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        string verification(string xml_url, string xsd_url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        System.Threading.Tasks.Task<string> verificationAsync(string xml_url, string xsd_url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXMLDoc", ReplyAction="http://tempuri.org/IService1/GetXMLDocResponse")]
        string GetXMLDoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXMLDoc", ReplyAction="http://tempuri.org/IService1/GetXMLDocResponse")]
        System.Threading.Tasks.Task<string> GetXMLDocAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project4_Site.XMLService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project4_Site.XMLService.IService1>, Project4_Site.XMLService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addPark(Project4_Site.XMLService.Park park) {
            base.Channel.addPark(park);
        }
        
        public System.Threading.Tasks.Task addParkAsync(Project4_Site.XMLService.Park park) {
            return base.Channel.addParkAsync(park);
        }
        
        public string verification(string xml_url, string xsd_url) {
            return base.Channel.verification(xml_url, xsd_url);
        }
        
        public System.Threading.Tasks.Task<string> verificationAsync(string xml_url, string xsd_url) {
            return base.Channel.verificationAsync(xml_url, xsd_url);
        }
        
        public string GetXMLDoc() {
            return base.Channel.GetXMLDoc();
        }
        
        public System.Threading.Tasks.Task<string> GetXMLDocAsync() {
            return base.Channel.GetXMLDocAsync();
        }
    }
}
